### ISSUE TITLE
Make sure to sanitize data using WordPress methods

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/tamwood-spring-2018#10]
You can test this by adding some JavaScript to a field when editing a post e.g. 
```<script>alert('wubalubadubdub');</script>```

You can sanitize data using methods like:
- esc_html
- esc_url
- wp_kses
- wp_kses_post

The way you use them:

```<?php echo esc_html(CFS()->get( 'hero_title' )); ?>```

https://github.com/redacademy/tamwood-spring-2018/blob/1c709673da04f26ba3677cb7ce1d8df88505cb10/themes/tamwood-theme/front-page.php#L14

**Comment by rcass** [comment]
If you need more resources about sanitizing data, here are the lesson slides about it [here](https://red-wdp.herokuapp.com/slides/wp-security-deployment-and-hosting-slides/#10)

**Comment by aroerick** [comment]
commits 
1e16a1a5fb25be4cfa36dbfae77dcd1cb8c80baa
819ee92c7402699932a5a9c59425e69b7cb29784
df999b52930abdebf5e62079d95c7b6c9c537626

I really hope I found everything. Oh boy.
