### ISSUE TITLE
index.php: Extra line of code

### ISSUE THREAD

**Issue by rcass** [redacademy/tamwood-spring-2018#11]
In the index.php, the fall back file or default file, I found this line of code:

https://github.com/redacademy/tamwood-spring-2018/blob/1c709673da04f26ba3677cb7ce1d8df88505cb10/themes/tamwood-theme/index.php#L13

I don't think this is necessary, but let me know if it is suppose to be there.

**Comment by aroerick** [comment]
Was apparently for testing purposes. Removed.
