### ISSUE TITLE
Contact Page: Use default functionality rather then extra CFS fields

### ISSUE THREAD

**Issue by rcass** [redacademy/tamwood-spring-2018#18]
On the contact page, you are using CFS to create new fields for the page title, body content, and contact form.

The page title and body content do not need CFS at all. You should use the default title area and WYSIWYG. For the form, I really don't think you need a separate place either, I would try it in just the same WYSIWYG as everything else. Then use the CSS to move it to the area it should be located according to the design.

**Comment by aroerick** [comment]
Changed it back to a regular WYSIWYG. Got a little CFS trigger happy in there at some points.
