### ISSUE TITLE
Duplicate ID site-navigation

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/tamwood-spring-2018#2]
It's ok if you have a duplicate menu for mobile & desktop however make sure that each has a unique id

https://github.com/redacademy/tamwood-spring-2018/blob/1c709673da04f26ba3677cb7ce1d8df88505cb10/themes/tamwood-theme/header.php#L37

**Comment by aroerick** [comment]
Updated. #site-navigation-mobile & #site-navigation-desktop

**Comment by rcass** [comment]
@aroerick do you mind just referencing the commit that you made that change? Just trying to verify this is resolved :)
