### ISSUE TITLE
Mobile Menu: Submenu issue, unable to click submenu items

### ISSUE THREAD

**Issue by rcass** [redacademy/tamwood-spring-2018#7]
![screen shot 2018-06-21 at 10 16 59 am](https://user-images.githubusercontent.com/5028555/41734757-bc7e8d28-753c-11e8-87f6-5a5f433cea37.png)

TO DO:

- [x] Make sure a user can click on the sub menu items

- [x] Make icons that indicate a submenu clickable

**Comment by aroerick** [comment]
Finished it.
